# Generated by Django 4.1.5 on 2023-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_alter_batalla_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercito1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandantes', models.CharField(max_length=100)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(max_length=100)),
                ('caballeria', models.CharField(max_length=100)),
                ('proyectiles', models.CharField(max_length=100)),
                ('tropas_elite', models.CharField(max_length=100)),
                ('asedio', models.CharField(max_length=100)),
                ('elefantes', models.CharField(max_length=100)),
                ('mercenarios', models.CharField(max_length=100)),
                ('bajas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercito2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandantes', models.CharField(max_length=100)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(max_length=100)),
                ('caballeria', models.CharField(max_length=100)),
                ('proyectiles', models.CharField(max_length=100)),
                ('tropas_elite', models.CharField(max_length=100)),
                ('asedio', models.CharField(max_length=100)),
                ('elefantes', models.CharField(max_length=100)),
                ('mercenarios', models.CharField(max_length=100)),
                ('bajas', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='batalla',
            old_name='beligerantes',
            new_name='resultado',
        ),
        migrations.DeleteModel(
            name='Ejercito',
        ),
    ]
