# Generated by Django 4.1.5 on 2023-06-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_ejercito1_ejercito2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandantes', models.CharField(max_length=100)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(max_length=100)),
                ('caballeria', models.CharField(max_length=100)),
                ('proyectiles', models.CharField(max_length=100)),
                ('tropas_elite', models.CharField(max_length=100)),
                ('bajas', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejercito1',
        ),
        migrations.DeleteModel(
            name='Ejercito2',
        ),
        migrations.RenameField(
            model_name='batalla',
            old_name='resultado',
            new_name='beligerantes',
        ),
        migrations.AddField(
            model_name='ejercito',
            name='batalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercitos', to='battles.batalla'),
        ),
    ]
