# Generated by Django 4.1.5 on 2023-06-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_ejercito_delete_ejercito1_delete_ejercito2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercito1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandantes', models.CharField(max_length=100)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(max_length=100)),
                ('caballeria', models.CharField(max_length=100)),
                ('proyectiles', models.CharField(max_length=100)),
                ('tropas_elite', models.CharField(max_length=100)),
                ('mercenarios', models.CharField(max_length=100)),
                ('asedio', models.CharField(max_length=100)),
                ('criaturas', models.CharField(max_length=100)),
                ('bajas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercito2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandantes', models.CharField(max_length=100)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(max_length=100)),
                ('caballeria', models.CharField(max_length=100)),
                ('proyectiles', models.CharField(max_length=100)),
                ('tropas_elite', models.CharField(max_length=100)),
                ('mercenarios', models.CharField(max_length=100)),
                ('asedio', models.CharField(max_length=100)),
                ('criaturas', models.CharField(max_length=100)),
                ('bajas', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='batalla',
            name='resultado',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
        migrations.DeleteModel(
            name='Ejercito',
        ),
    ]
