# Generated by Django 4.1.5 on 2023-06-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0008_alter_batalla_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batalla',
            name='beligerantes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ejercito1',
            name='comandantes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ejercito2',
            name='comandantes',
            field=models.CharField(max_length=200),
        ),
    ]
