# Generated by Django 4.1.5 on 2023-06-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_alter_batalla_beligerantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercito1',
            name='batalla',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battles.batalla'),
        ),
        migrations.AddField(
            model_name='ejercito2',
            name='batalla',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battles.batalla'),
        ),
    ]
