# Generated by Django 4.1.5 on 2023-06-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_ejercito1_batalla_ejercito2_batalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercito1',
            name='titulo',
            field=models.CharField(default='Valor predeterminado', max_length=50),
        ),
        migrations.AddField(
            model_name='ejercito2',
            name='titulo',
            field=models.CharField(default='Valor predeterminado', max_length=50),
        ),
    ]
