# Generated by Django 4.1.5 on 2023-06-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_ejercito1_titulo_ejercito2_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercito2',
            new_name='Ejercito',
        ),
        migrations.DeleteModel(
            name='Ejercito1',
        ),
    ]
