# Generated by Django 4.1.5 on 2023-06-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_rename_ejercito2_ejercito_delete_ejercito1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercito',
            new_name='EjercitoVencedor',
        ),
        migrations.CreateModel(
            name='EjercitoVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Valor predeterminado', max_length=50)),
                ('comandantes', models.CharField(max_length=200)),
                ('fuerzas_combate', models.CharField(max_length=100)),
                ('infanteria', models.CharField(blank=True, max_length=100)),
                ('caballeria', models.CharField(blank=True, max_length=100)),
                ('proyectiles', models.CharField(blank=True, max_length=100)),
                ('tropas_elite', models.CharField(blank=True, max_length=100)),
                ('mercenarios', models.CharField(blank=True, max_length=100)),
                ('asedio', models.CharField(blank=True, max_length=100)),
                ('criaturas', models.CharField(blank=True, max_length=100)),
                ('bajas', models.CharField(max_length=100)),
                ('batalla', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battles.batalla')),
            ],
        ),
    ]
