# Generated by Django 4.1.5 on 2023-07-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='imagen',
        ),
    ]
