# Generated by Django 4.1.5 on 2023-07-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_usuarios_descripcion_usuarios_social_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='social_link',
        ),
    ]
