# Generated by Django 4.1.5 on 2023-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_infopersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonal',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
