# Generated by Django 4.1.5 on 2023-07-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_avatar_descripcion_avatar_enlace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='enlace',
        ),
    ]
